// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.projetresergraphql.stubs;

public interface GetReservationsByClientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationsByClientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ReservationGrpc reservations = 1;</code>
   */
  java.util.List<com.projetresergraphql.stubs.ReservationGrpc> 
      getReservationsList();
  /**
   * <code>repeated .ReservationGrpc reservations = 1;</code>
   */
  com.projetresergraphql.stubs.ReservationGrpc getReservations(int index);
  /**
   * <code>repeated .ReservationGrpc reservations = 1;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .ReservationGrpc reservations = 1;</code>
   */
  java.util.List<? extends com.projetresergraphql.stubs.ReservationGrpcOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <code>repeated .ReservationGrpc reservations = 1;</code>
   */
  com.projetresergraphql.stubs.ReservationGrpcOrBuilder getReservationsOrBuilder(
      int index);
}
