// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.projetresergraphql.stubs;

public interface GetReservationsByClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationsByClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientId = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
