// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.projetresergraphql.stubs;

public final class ReservationProto {
  private ReservationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationGrpc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationGrpc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationsByClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationsByClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationsByClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationsByClientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\"{\n\017ReservationGrpc\022\n" +
      "\n\002id\030\001 \001(\t\022\020\n\010clientId\030\002 \001(\t\022\021\n\tchambreI" +
      "d\030\003 \001(\t\022\021\n\tdateDebut\030\004 \001(\t\022\017\n\007dateFin\030\005 " +
      "\001(\t\022\023\n\013preferences\030\006 \001(\t\"\033\n\031GetAllReserv" +
      "ationsRequest\"D\n\032GetAllReservationsRespo" +
      "nse\022&\n\014reservations\030\001 \003(\0132\020.ReservationG" +
      "rpc\"?\n\026SaveReservationRequest\022%\n\013reserva" +
      "tion\030\001 \001(\0132\020.ReservationGrpc\"@\n\027SaveRese" +
      "rvationResponse\022%\n\013reservation\030\001 \001(\0132\020.R" +
      "eservationGrpc\"\'\n\031GetReservationByIdRequ" +
      "est\022\n\n\002id\030\001 \001(\t\"C\n\032GetReservationByIdRes" +
      "ponse\022%\n\013reservation\030\001 \001(\0132\020.Reservation" +
      "Grpc\"&\n\030DeleteReservationRequest\022\n\n\002id\030\001" +
      " \001(\t\"M\n\030UpdateReservationRequest\022\n\n\002id\030\001" +
      " \001(\t\022%\n\013reservation\030\002 \001(\0132\020.ReservationG" +
      "rpc\"B\n\031UpdateReservationResponse\022%\n\013rese" +
      "rvation\030\001 \001(\0132\020.ReservationGrpc\"=\n\031Delet" +
      "eReservationResponse\022\017\n\007message\030\001 \001(\t\022\017\n" +
      "\007success\030\002 \001(\010\"2\n\036GetReservationsByClien" +
      "tRequest\022\020\n\010clientId\030\001 \001(\t\"I\n\037GetReserva" +
      "tionsByClientResponse\022&\n\014reservations\030\001 " +
      "\003(\0132\020.ReservationGrpc2\353\003\n\022ReservationSer" +
      "vice\022J\n\017AllReservations\022\032.GetAllReservat" +
      "ionsRequest\032\033.GetAllReservationsResponse" +
      "\022D\n\017SaveReservation\022\027.SaveReservationReq" +
      "uest\032\030.SaveReservationResponse\022J\n\017Reserv" +
      "ationById\022\032.GetReservationByIdRequest\032\033." +
      "GetReservationByIdResponse\022N\n\025DeleteRese" +
      "rvationById\022\031.DeleteReservationRequest\032\032" +
      ".DeleteReservationResponse\022[\n\026Reservatio" +
      "nsByClientId\022\037.GetReservationsByClientRe" +
      "quest\032 .GetReservationsByClientResponse\022" +
      "J\n\021UpdateReservation\022\031.UpdateReservation" +
      "Request\032\032.UpdateReservationResponseB2\n\034c" +
      "om.projetresergraphql.stubsB\020Reservation" +
      "ProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReservationGrpc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReservationGrpc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationGrpc_descriptor,
        new java.lang.String[] { "Id", "ClientId", "ChambreId", "DateDebut", "DateFin", "Preferences", });
    internal_static_GetAllReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetAllReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAllReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_SaveReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SaveReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveReservationRequest_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_SaveReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SaveReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_GetReservationByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetReservationByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetReservationByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetReservationByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationByIdResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_UpdateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_UpdateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReservationRequest_descriptor,
        new java.lang.String[] { "Id", "Reservation", });
    internal_static_UpdateReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_UpdateReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_DeleteReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_DeleteReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationResponse_descriptor,
        new java.lang.String[] { "Message", "Success", });
    internal_static_GetReservationsByClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GetReservationsByClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationsByClientRequest_descriptor,
        new java.lang.String[] { "ClientId", });
    internal_static_GetReservationsByClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_GetReservationsByClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationsByClientResponse_descriptor,
        new java.lang.String[] { "Reservations", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
