// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.projetresergraphql.stubs;

public interface SaveReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ReservationGrpc reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.ReservationGrpc reservation = 1;</code>
   * @return The reservation.
   */
  com.projetresergraphql.stubs.ReservationGrpc getReservation();
  /**
   * <code>.ReservationGrpc reservation = 1;</code>
   */
  com.projetresergraphql.stubs.ReservationGrpcOrBuilder getReservationOrBuilder();
}
